autobotego_adefde_loss:
  _target_: nuplan.planning.training.modeling.metrics.autobotego_metrics.AutobotsADEFDELoss
  _convert_: 'all'

  entropy_weight: 40
  kl_weight: 20
  use_FDEADE_aux_loss: true
